### ISSUE TITLE
Exporting events

### ISSUE THREAD

**Issue by ericadeefox** [BallStateCBER/muncie_events3#15]
The ability to export events from iCal, Google, Outlook, and Yahoo!* needs rebuilt still from Cake2 to Cake3.

_*I am totally okay with not giving anyone the ability to export to Yahoo!_

**Comment by ericadeefox** [comment]
Can export events to Google Calendar now.

**Comment by ericadeefox** [comment]
- [x] I'm not going to support Yahoo! Calendar.

**Comment by PhantomWatson** [comment]
You're being totally unsupportive right now.

**Comment by ericadeefox** [comment]
A short list of things that the ICS exporter needs to do in order to be done:
- [ ] Actually export iCalendar data. (As opposed to error messages.)
- [ ] Set $filename and export files using $filename, not foo.bar.
- [ ] Links in actions.ctp reset to reflect /events/ics/view rather than event/view?ext=ics

However the ICS exporter can, well, export error messages in the form of foo.bar files. Slowly but surely.

**Comment by ericadeefox** [comment]
`2017-04-26 11:52:10 Warning: Warning (512): Method App\View\Helper\iCalHelper::iCalLoader does not exist in [/var/www/html/muncie_events3/vendor/cakephp/cakephp/src/View/Helper.php, line 139]`

**Comment by PhantomWatson** [comment]
I suggest setting up [file extension routing](https://book.cakephp.org/3.0/en/development/routing.html#routing-file-extensions) like this:
- For an event viewable at `/event/123` (routed to `/events/view/123`)
- `$this->Html->link()`s to download importable files have this URL array structure:

```
[
    'controller' => 'Events',
    'action' => 'export',
    $eventId,
    '_ext' => 'ics
]
```
(or whatever your action name happens to be)
- Set up routing so that those links appear as `/event/123.ics`

Super clean and simple to just be able to tack a file extension at the end of the event's URL to get the download.

**Comment by ericadeefox** [comment]
Got it. On the Cake2 site it's set up so that .ics files are downloaded from /event/123?ext=ics, I'm all about /event/123.ics as a much simpler method.
