### ISSUE TITLE
Notify Slack when events need moderation

### ISSUE THREAD

**Issue by PhantomWatson** [BallStateCBER/muncie_events3#30]
Send a notification to Slack (perhaps in a new #muncieevents channel) when new events get posted in order to reduce the time between posting and moderator actions.

**Bonus points:** Divide up moderators by days of the week and mention who's currently on duty in the messages, e.g. 
> **Graham:** The event "Competitive Pantomime Regional Championships" has been posted by M. Goldman

**Comment by ericadeefox** [comment]
which days of the week do you want?

**Comment by PhantomWatson** [comment]
Sunday, Tuesday, Thursday, and Saturday.

**Comment by ericadeefox** [comment]
got it.

**Comment by ericadeefox** [comment]
What do you want to do about events series? One notification for the whole series, or a notification for each individual event?

**Comment by ericadeefox** [comment]
Idea: what if it DMs you when an event is posted, instead of the #muncieevents channel?

**Comment by PhantomWatson** [comment]
I'm not sure about event series. We need a more sophisticated way of editing an entire series at once, but we're not there yet. For now, one notification for each event seems like the most straightforward answer.

Direct messages sounds like a good approach.

**Comment by ericadeefox** [comment]
If you go to /events/edit-series/:id you can edit a whole series at once. So I've just been doing that.

**Comment by ericadeefox** [comment]
So here's where this is at:

1. On Mondays, Wednesdays, and Fridays, the bot DMs me about new events & series posted. On Tuesdays, Thursdays, and weekends, the bot DMs you.
2. Here's what the DM looks like: 
![image](https://user-images.githubusercontent.com/12422542/34457187-90e5f086-ed77-11e7-868f-1cdab7adb3b1.png)
3. For single events, it just takes you to `/events/edit/:id` and that's pretty easy.
4. For event series, it takes you to `/events/edit-series/:id`, which of course `:id` in that case is the `series_id`. In the `edit-series` method, you can edit all the events in the series at once: their titles, images, tags, all that. So you use `edit-series` for stuff like when Moth has Stitch n Bitch, and there's no variance between the events. I've thoroughly tested `edit-series` in 3.x (I'm not sure it actually worked in 2.x and there was nothing that linked to it) and it works fine.
5. Finally, right now this alerts us whenever _any_ type of event is posted, regardless if it needs moderation. I should probably change that, but I also wanted to have it alert us whenever because sometimes the events need edited regardless.

**Comment by PhantomWatson** [comment]
Oh, I didn't register that you had upgraded the event series editing page. Wonderful!

**Comment by ericadeefox** [comment]
Yep it was one of the methods I'm proud I upgraded. Took a while to get it to work but 500% worth it.

**Comment by ericadeefox** [comment]
I'm gonna go ahead and close this for now since everything works. If we want to go to only getting Slack notifications when unmoderated events as opposed to all events go through, just let me know and I'll write the short li'l old if statement that makes that happen.

**Comment by PhantomWatson** [comment]
Sounds good. Since "moderation" is ambiguous for this particular project, it's worth clarifying that:
- Slack notifications (and any other form of administrator alerts) happen for all new events, regardless of their automatic published / unpublished status
- This is to help guide administrators to switch events from 'unapproved' to 'approved', editing events as necessary, and deleting anything that violates the rules

**Comment by ericadeefox** [comment]
Maybe we could make an actual guide? I guess the rules are guide enough.
