### ISSUE TITLE
Big Official 2.x to 3.x Upgrade List of Issues

### ISSUE THREAD

**Issue by ericadeefox** [BallStateCBER/muncie_events3#33]
- [x] The month method URL reads /month/MM/YYYY. However, due to weird counting or whatever is happening there, advancing past December into January reads not as /01/YYYY, but rather /13/YYYY of the previous year. e.g. if you want to check out January 1992, you can put /01/1992 into the URL, but you can also put /25/1990 into the URL.

- [x] **Month widgets only show the current month; using the prev & next buttons take you to month pages. Clicking prev & next buttons does not open the in-widget month.**

- [x] Feed widgets show all the events at once, rather than a couple weeks at a time with a "More Events" button.

- [x] Clicking events in the feed widgets opens the event page, rather than the in-widget event.

- [x] Locations & custom tags don't autocomplete in the event form.

- [ ] **The mailing list _might_ work? I don't know if it does and I don't know how to test it.**

- [x] "More Events" button appears 100% of the time in indexes, even if there are literally no events to index.

- [x] The paginator buttons are ugly & awkward.

- [x] **The index breaks if the events are more than two weeks apart.**

**BOLD INDICATES HIGH PRIORITY**

**Comment by PhantomWatson** [comment]
- Event form
  - [ ] "remove" buttons appear below input fields instead of beside them
  - [ ] "submit" button needs Bootstrap classes added
- Mailing list signup page
  - [ ] The "all events" option for "event types" is no longer selected by default
  - [ ] Checkboxes for event types aren't selected by default
  - [ ] Under "frequency", the weekly/daily options are missing and only the "custom" option is shown
- Other
  - [ ] A successful login doesn't redirect to home page, but just loads the login page again
  - [ ] The ME icon in the logo needs `cursor: pointer`
  - [ ] New JavaScript error: Lines like `muncieEvents.populatedDates['11-2009'] = [01,06,08,15,22,25,27,29];` generate errors for numbers that start with zero. This could be adapted to remove the leading zeros, or these values could be changed to strings.
  - [ ] In image_manager.js, on line 242 (`url: '/images/user_images/'+ImageManager.user_id,`), something's not setting `ImageManager.user_id` and the URL ends up being .../null
  - [ ] /general (and other category pages) is showing events from all categories
  - [ ] I recommend copying code from https://github.com/BallStateCBER/datacenter-plugin-cakephp3/blob/master/src/Template/Element/pagination.ctp to update the pagination element.
  - [ ] In /tag/... pages, the words "upcoming" and "past" are no longer capitalized
  - [ ] On /tags, the category icons need `cursor: pointer`

**Comment by ericadeefox** [comment]
>  "remove" buttons appear below input fields instead of beside them

This is how it is in the 2.x version now too. Should I change the both of them?

**Comment by PhantomWatson** [comment]
I'm only seeing that issue in the CakePHP 3 version:
![image](https://user-images.githubusercontent.com/1965565/33509626-2e80a150-d6d1-11e7-9ffa-efc90fab5825.png)

The CakePHP 2 version looks correct:
![image](https://user-images.githubusercontent.com/1965565/33509638-409f7f3c-d6d1-11e7-97af-72f75563f56c.png)

**Comment by ericadeefox** [comment]
> I recommend copying code from https://github.com/BallStateCBER/datacenter-plugin-cakephp3/blob/master/src/Template/Element/pagination.ctp to update the pagination element.

It wouldn't match the 2.x version if I did that, though. The current pagination element I've got uses Bootstrap pagination elements and is similar in design to the one I made for the 2.x version.

**Comment by ericadeefox** [comment]
> New JavaScript error: Lines like muncieEvents.populatedDates['11-2009'] = [01,06,08,15,22,25,27,29]; generate errors for numbers that start with zero. This could be adapted to remove the leading zeros, or these values could be changed to strings.

Do you have an example of the error? Because there's no error like this on my end, nothing in the console etc. So I'm lost.

**Comment by ericadeefox** [comment]
> Under "frequency", the weekly/daily options are missing and only the "custom" option is shown

This, I did on purpose to sort of downsize the form, so if someone wants an email every day then they can check every checkbox, or just the ones they'd like depending on the day, or if they'd like it weekly they can do that too.

**Comment by PhantomWatson** [comment]
> SyntaxError: 08 is not a legal ECMA-262 octal constant

A quick way to fix the problem would be in `AppController::beforeRender()`, changing the line
```
$populated["$month-$year"][] = $day;
```
to
```
$populated["$month-$year"][] = "'$day'";
```

But the better solution is probably to change this line in `links_primary.ctp`:
```
"muncieEvents.populatedDates['$monthYear'] = [".implode(',', $days)."];"
```
to
```
"muncieEvents.populatedDates = " . json_encode($populated) . ";"
```

**Comment by ericadeefox** [comment]
^Done. I wonder why I never got the error message.
